# Generated by Django 2.2.6 on 2020-02-10 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portal.models
import rest_framework.compat


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('pinned', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('short', models.BooleanField(default=True)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnnounceWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_begin', models.TimeField()),
                ('orders_end', models.TimeField()),
                ('delivery', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RealtimeStatusWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=False)),
                ('lan', models.CharField(choices=[(portal.models.Status('ok'), 'ok'), (portal.models.Status('unstable'), 'unstable'), (portal.models.Status('fail'), 'fail')], default='O', max_length=1)),
                ('wan', models.CharField(choices=[(portal.models.Status('ok'), 'ok'), (portal.models.Status('unstable'), 'unstable'), (portal.models.Status('fail'), 'fail')], default='O', max_length=1)),
                ('csgo', models.CharField(choices=[(portal.models.Status('ok'), 'ok'), (portal.models.Status('unstable'), 'unstable'), (portal.models.Status('fail'), 'fail')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_device_nb', models.IntegerField(default=3, validators=[rest_framework.compat.MinValueValidator(limit_value=2)])),
                ('role', models.CharField(choices=[(portal.models.Role('Player'), 'Player'), (portal.models.Role('Manager'), 'Manager'), (portal.models.Role('Guest'), 'Guest'), (portal.models.Role('Staff Member'), 'Staff Member'), (portal.models.Role('Administrator'), 'Administrator')], default='Player', max_length=1)),
                ('tournament', models.CharField(max_length=100, null=True)),
                ('team', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Computer', max_length=100)),
                ('ip', models.CharField(max_length=15)),
                ('mac', models.CharField(max_length=17)),
                ('area', models.CharField(default='LAN', max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
