FROM ubuntu:latest

EXPOSE 80
WORKDIR /app

ENV LANG=C.UTF-8

# installing deps

RUN apt-get update
RUN apt-get install -y supervisor python3 python3-pip ipset iptables sudo nginx ruby ruby-dev
RUN gem install sass

COPY requirements.txt /app/
RUN pip3 install -r requirements.txt

COPY langate2000-supervisor.conf /etc/supervisor/supervisord.conf

# nginx setup

COPY langate2000-nginx.conf /etc/nginx/sites-enabled/default
RUN mkdir -p /var/www/html/static

# netcontrol

ADD langate2000-netcontrol /app/langate2000-netcontrol

# theming

ADD theming /app/theming

WORKDIR /app/theming/

RUN sass insalan.scss langate.css

# django

ADD langate /app/langate

RUN cp /app/theming/langate.css /app/langate/static/css/

WORKDIR /app/langate/

RUN python3 manage.py makemigrations --noinput
RUN python3 manage.py migrate --noinput

RUN python3 manage.py collectstatic --noinput
RUN echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('root', '', 'rien')" | python3 manage.py shell

CMD [ "supervisord", "-c", "/etc/supervisor/supervisord.conf" ]
